Cargo.toml, src/linux/mod.rs, src/traits.rs
- The way it counts package is by returning the number of entries in
/var/lib/flatpak/app. This path is where system-wide flatpaks are
installed meaning it currently doesn't count per-user
packages, but this will be added in the next patch.
=> Patch to add support for Flatpak (Linux Only)

src/extra.rs, src/lib.rs, src/linux/mod.rs, src/traits.rs
- This patch is as efficient as it gets, the way it works is it returns
the number of entries in `/var/lib/eopkg/package`, meaning no direct
interaction between Macchina and eopkg.
- For some odd reason, this wasn't included in the codebase, I
mistakingly included eopkg support in Macchina's wiki, but this patch
makes up for that silly mistake. My apologies to eopkg users.
- This patch also includes more documentation, and adds
examples to functions that previously did not include them.
=> ✨ This patch adds support for eopkg package manager

Cargo.toml, src/linux/mod.rs, src/macos/mod.rs, src/netbsd/mod.rs, src/openwrt/mod.rs, src/shared/mod.rs, src/traits.rs
This will allow Macchina to display logical CPU cores, just like always.
=> Include a way to query logical CPU cores

src/linux/mod.rs, src/netbsd/mod.rs, src/shared/mod.rs
- Another small change was that I modified the return value to be -1 when
get_process_status_field() fails.
- get_process_status_field() was renamed to get_shell_ppid() as this
seems more appropriate for the job that it accomplishes.
- Another check has been added to ensure that in case of terminal fetching
failure, the program should not return an unexpected value: terminal_name() will
only continue if it receives a PID that is not -1.
=> 🚩 NetBSD: Terminal fetching without `ps`

src/extra.rs, src/linux/mod.rs, src/netbsd/mod.rs, src/shared/mod.rs
- All package managers should now return `None` when they fail to fetch.
- `snap` and `dpkg` now properly fetch package information.
=> 🐛 Package manager bug fixes

Cargo.toml, src/android/mod.rs, src/android/system_properties.rs
<del> Also after I removed the sysctl ~~ stuff from the `AndroidKernelReadout` it seems to fail, Which didn't happen when I just introduced `libc::gethostname` without removing anything else. </del>
Fixed now.
=> Check android kernel and hosname from libc

Cargo.toml, build.rs, src/android/system_properties.h, src/android/system_properties.rs
remove build_android()
Removing this improves the build time and doesn't include unnecessary code.
=> Remove bindgen

Cargo.toml, build.rs, src/linux/mod.rs, src/netbsd/mod.rs, src/traits.rs
Added a basic (X11 only) resolution implementation using X11 bindings.
It should theoretically work on NetBSD just as it does on Linux.
- Wayland support, the Linux world has been moving slowly but steadily towards adopting Wayland and a lot of people are running it as their daily driver.
- This method requires that the user is in a graphical environment, resolution will fail to fetch in a TTY.
**I can confirm this works on my one screen setup, but more testing should be done.**
=> Resolution support

Cargo.toml, build.rs, src/netbsd/mod.rs, src/netbsd/x11_ffi.rs
X11 libraries weren't being properly linked, this PR solves this issue.
It also provides a way to tell libmacchina where to find X11 libraries (instead of a hardcoded path, `/usr/X11R7/lib` through an environment variable called `LIBMAC_X11_LIB_PATH`.
=> 🐛 Fix Resolution Readout for NetBSD

Cargo.toml, build.rs, src/lib.rs
Added a function in lib.rs called function which returns a static string containing the version and commit hash.
=> libmacchina show commit hash in version info

src/netbsd/mod.rs, src/shared/mod.rs
This won't fix macchina's build errors on the NetBSD side because of a version incompatibility it is currently experiencing.
=> NetBSD: use statvfs rather than statfs to query used disk space

src/netbsd/mod.rs
See the end of #55 for the reasons behind this PR.
=> netbsd::GeneralReadout::resolution: return MetricNotAvailable

Cargo.toml, src/shared/mod.rs, src/windows/mod.rs
This change fixes #88 but since the discussion there was not final, I would understand if the alternative method would be preferred.
The implementation in this pull request would also allow to not specify an interface. In this case the `local-ip-address` crate chooses some sensible defaults to determine the local IP address.
=> Use 'local-ip-address' crate instead of 'if-addrs'

src/android/mod.rs, src/freebsd/mod.rs, src/linux/mod.rs, src/macos/mod.rs, src/netbsd/mod.rs, src/traits.rs, src/windows/mod.rs
This is the refactoring mentioned in #95.
**Summary:**
- Removes `version()` and `name()` from `ProductReadout`
- Fixes documentation for `ProductReadout` to not be mistaken for operating system information
- Fix the implementation for macOS & Windows that reported OS information instead of device information
⚠ **Important:** Please double check the implementation for anything but Windows, because I don't have a running system of those types.
=> Refactoring of ProductReadout

Cargo.toml, src/android/mod.rs, src/freebsd/mod.rs, src/lib.rs, src/linux/mod.rs, src/macos/mod.rs, src/netbsd/mod.rs, src/openwrt/mod.rs, src/shared/mod.rs, src/traits.rs, src/windows/mod.rs
Moved the following method:
- `GeneralReadout::local_ip(interface)` to `NetworkReadout::logical_address(interface)`
Added the following new methods:
- `NetworkReadout::physical_address(interface)`
- `NetworkReadout::rx_bytes(interface)`
- `NetworkReadout::tx_bytes(interface)`
- `NetworkReadout::rx_packets(interface)`
- `NetworkReadout::tx_packets(interface)`
The above methods have only been implemented by `LinuxNetworkReadout`.
=> BREAKING CHANGE: Introduce a new readout trait, "NetworkReadout".

Cargo.toml, src/android/mod.rs, src/freebsd/mod.rs, src/lib.rs, src/linux/mod.rs, src/macos/mod.rs, src/netbsd/mod.rs, src/openwrt/mod.rs, src/traits.rs, src/windows/mod.rs
This is probably a controversial change. The idea behind this is to make it more obvious, which readouts/functions are supported in the corresponding targets.
**Advantage:** It is easier to determine which functions are implemented for a specific target and what might need to be added in the future.
**Disadvantage:** It might seem messier to have all those `ReadoutError::NotImplemented`.
---
❗ **Important:** I did not yet make the change in the entire library and it therefore does not compile yet. I want to gather some feedback if this is even something that would be accepted, before I finish this work.
=> Explicitly mark readouts that are not implemented

Cargo.toml, src/shared/mod.rs, src/windows/mod.rs
The implementation for fetching cargo packages in the `shared` folder works perfectly fine under Windows.
The only reason, why it was not working before was the usage of the `which` function that doesn't work correctly under Windows.
=> Fix the readout of cargo packages on Windows

src/extra.rs, src/shared/mod.rs
I am not so sure about the `#![allow(dead_code)]` or if we should find a better solution for the `extra` module.
=> Fix build warnings

Cargo.toml, src/traits.rs, src/windows/mod.rs
This change adds support for the [Scoop](https://scoop.sh/) installer on Windows.
It works by querying the `scoop export` command that lists all the installed packages and we can count the number of lines.
=> Count installed Scoop packages if available

src/android/mod.rs, src/extra.rs, src/linux/mod.rs
- Linux: removed many needless checks
- When counting packages, acquire the value of $HOME once instead
of potentially doing it multiple times (in `count_linuxbrew()` and `count_flatpak()`)
I'm not sure if this is necessary, but... we'll see.
- Renamed `list_dir_entries()` to `get_entries()` to better match its
purpose
- `get_entries()` returns an optional value. 
- The good: less allocations, as the previous implementation allocates a vector
before it even looks for the directory's entries.
- The bad: lots of "if let some-ing", I think this is a fair trade-off.
=> refactor: list_dir_entries() returns an optional and other enhacements

Cargo.toml, src/windows/mod.rs
As discussed in #107 I refactored the Scoop package count by using the `SCOOP` environment variable if available, or the default path `C:\Users\<user>\scoop`.
I am happy to say that this improved performance:
| Note | Mean [ms] | Min [ms] | Max [ms] |
|---|---:|---:|---:|
| Before this PR | 54.5 ± 7.6 | 50.6 | 104.5 |
| PR without Scoop installed | 43.0 ± 0.9 | 39.9 | 45.1 |
| PR with Scoop installed | 43.5 ± 0.9 | 41.5 | 46.3 |
=> Improve Scoop package count performance

.github/workflows/libmacchina.yml, src/android/mod.rs, src/windows/mod.rs
I noticed that during the CI build we execute `cargo fmt` which applies the code format to all files. However since those changes will not be committed in any way, it is not ensured that no code format violations are introduced.
This PR uses the more appropriate `cargo fmt -- --check` command that fails if the code format is not valid.
=> Code format check during CI build

build.rs, src/macos/mach_ffi.rs, src/macos/mod.rs
Adds the macOS backlight readout implementation. Works on my M1 Macbook.
=> Mac: Add backlight readout

src/linux/mod.rs
To get an accurate count of portage packages only count the amount of 2 level deep directories. First level are package categories and he third are per package metadata and thus both shouldn't be counted.
=> fix portage package count

src/shared/mod.rs
The function count_cargo always return None.
The following code is dead code:
```rust
match read_dir.count() {
0 => None,
pkgs => Some(pkgs),
};
```
=> Fix cargo count

src/linux/mod.rs
This makes the value consistent with other tools and libraries such as the pfetch fetch utility and sysinfo rust crate
=> Use `MemAvailable` meminfo_value to calculate used memory

Cargo.toml, src/freebsd/mod.rs
This is for the most part the implementation from `sysinfo` that uses the `libc` crate to make the `CTL_KERN` and `KERN_BOOTTIME` syscalls. Taking this code snippet should not be an issue as `sysinfo` is licensed under the same license as this project.
=> Add FreeBSD uptime detection with `libc`

Cargo.toml, src/macos/mach_ffi.rs, src/macos/mod.rs
The `mach` crate (dependency for macOS) is no longer maintained: [RUSTSEC-2020-0168](https://rustsec.org/advisories/RUSTSEC-2020-0168)/https://github.com/fitzgen/mach/issues/63
[`mach2`](https://github.com/JohnTitor/mach2) is an active fork that works as a drop-in replacement.
All tests pass with `mach2` but I couldn't test all libmacchina features as I don't own a macOS device.
=> Replace mach with mach2

Cargo.toml, src/linux/mod.rs
This closes #154.
As mentioned by @CarterLi in https://github.com/Macchina-CLI/libmacchina/issues/154#issuecomment-1509428314, [fastfetch](https://github.com/LinusDierheimer/fastfetch) uses `librpm` to count RPM packages.
There are Rust bindings to librpm ([`librpm-sys`](https://github.com/rpm-software-management/librpm.rs)), however depending on that crate proved to introduce many build complications, and, more importantly, would require `librpm` to be installed on every system that `macchina`, or other binaries depending on `libmacchina`, are run on.
So I instead created a new small crate called [`rpm-pkg-count`](https://github.com/RubixDev/rpm-pkg-count) which directly links to `librpm` and uses fastfetch's method of retrieving the package count. To mitigate the second issue I make use …
=> feat: add support for RPM `ndb` databases

.github/workflows/libmacchina.yml, src/lib.rs, src/openwrt/mod.rs, src/traits.rs, src/windows/mod.rs
These are the same changes already applied to `macchina`: Macchina-CLI/macchina#311 & Macchina-CLI/macchina#313
- Replacement of `actions-rs` with [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) and explicit calls to the respective `cargo`/`cross` commands.
- Extracting the `cargo fmt` and `cargo clippy` steps into their own jobs.
- Fail `clippy` on warnings (required some minor code changes).
=> Improve CI workflow

src/linux/mod.rs
On Alpine Linux, packages can be counted by counting the amount of empty lines in `/lib/apk/db/installed`.
On my test VM, this takes about 5ms compared to 80ms with the previous method with 82 packages installed.
I left the previous counting method as fallback, in case there are systems that use `apk` where the new one does not work.
Related to https://github.com/Gobidev/pfetch-rs/issues/48
=> Faster package count on Alpine Linux

src/macos/mod.rs
https://www.apple.com/newsroom/2024/06/macos-sequoia-takes-productivity-and-intelligence-on-mac-to-new-heights/
=> add macos 15 version name

src/linux/mod.rs
Some minimal distros don't come with the pciutils package, or have the pci.id file in a different location that isn't picked up by pciid-parser.\
This is just a simple fix to throw an error, rather than a panic.
=> Removed panic if local gpu db is not able to be read

.github/workflows/libmacchina.yml, CHANGELOG.md, Cargo.toml, README.md, build.rs, src/android/mod.rs, src/dirs.rs, src/extra.rs, src/freebsd/mod.rs, src/lib.rs, src/linux/mod.rs, src/linux/pci_devices.rs, src/macos/mach_ffi.rs, src/macos/mod.rs, src/netbsd/mod.rs, src/openwrt/mod.rs, src/shared/mod.rs, src/traits.rs, src/windows/mod.rs, src/winman.rs
Just a simple rebase for the 8.0.0 branch
=> fix: rebase `8.0.0` branch with the latest changes from `main`

src/android/mod.rs, src/freebsd/mod.rs, src/linux/mod.rs, src/macos/mod.rs, src/netbsd/mod.rs, src/openwrt/mod.rs, src/traits.rs, src/windows/mod.rs
First of all, thanks for that amazing library, the performance and resource usage are really impressive compared to other similar libraries I've tried.
This PR implements swap for Linux, based on the already existing implementation for RAM that's using the `sysinfo` syscall.
It's probably possible to read that information from `/proc/meminfo` on Android, BSD and OpenWRT, but since I'm not having access to a device running BSD (and not enough motivation to test it on Android and OpenWRT because it's already too late in the day), this will be left unimplemented for now. I'd probably implement support for the mentioned operation systems as well if you're generally okay with this change.
Cheers.
=> feat: implement swap usage for linux

Cargo.toml, src/traits.rs, src/windows/mod.rs
closes #181 
Chocolatey package count is very straight forward, as it just counts the directories under `C:\ProgramData\chocolatey\lib`, which is consistent with `chocolatey list`.
For winget, I made use of an sqlite3 database under `C:\Users\Username\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db`, that contains a table `ids` with entries for each package that is explicitly installed with `winget`.
`winget list` lists a bunch more packages as installed by `winget`, e.g. `Microsoft OneDrive` and `Cortana`, but since those were not installed by the user using winget and those packages that were, are included, I think this is good as is.
Nevertheless, feedback by @Un1q32 or @Kodehawa from …
=> Add support for winget and chocolatey package counts on Windows

src/traits.rs
Add missing trait implementations in the `MemoryReadout` doctest.
=> Fix MemoryReadout doctest
